name: Get YouTube Video Transcriptions

on:
  issues:
    types: [created]

steps:
  - uses: actions/checkout@v1

  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.10.0

  - name: Install poetry
    run: |
      python -m pip install poetry==1.1.11

  - name: Configure poetry
    run: |
      python -m poetry config virtualenvs.in-project true

  - name: Cache the virtualenv
    uses: actions/cache@v2
    with:
      path: ./.venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    run: |
      python -m poetry install

  - name: Get issue number
      echo {{ github.event.number }}

  - name: Run Script
    run: |
      python -m poetry run python get_youtube_transcriptions/youtube.py {{ github.event.number }}

  - name: Commit new file 
    uses: stefanzweifel/git-auto-commit-action@v4    