name: Get YouTube Video Transcriptions

on:
  issues:
    types: [opened]

jobs:
  get_youtube_video_transcriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Get issue number
        run: |
          echo {{ github.event.number }}

      - name: Run get youtube transcriptions script
        run: |
          python -m poetry run python get_youtube_transcriptions/youtube.py ${{ github.event.issue.title }}

      - name: Commit new file
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue
